# Generated by Django 6.0.8 on 2026-08-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('teaching', 'Teaching'), ('billing', 'Billing'), ('financial_aid', 'Financial Aid'), ('sports', 'Sports'), ('boarding', 'Boarding'), ('conveyance', 'Conveyance'), ('general', 'General Inquiry')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
