# Generated by Django 6.0.8 on 2026-08-07 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True)),
                ('junior_secondary_overview', models.TextField(blank=True, help_text='Explains the JSS1–JSS3 curriculum structure to prospective parents.')),
                ('senior_secondary_overview', models.TextField(blank=True, help_text='Explains SS1–SS3 and the subject tracks (Science/Arts/Commercial).')),
            ],
            options={
                'verbose_name': 'Academics Page',
                'verbose_name_plural': 'Academics Page',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('junior', 'Junior Secondary (JSS1–JSS3)'), ('senior', 'Senior Secondary (SS1–SS3)')], max_length=10)),
                ('track', models.CharField(blank=True, choices=[('', '— Not applicable —'), ('core', 'Core (all senior students)'), ('science', 'Science Track'), ('arts', 'Arts Track'), ('commercial', 'Commercial Track')], help_text='Only relevant for Senior Secondary subjects.', max_length=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.department')),
            ],
            options={
                'ordering': ['department__order', 'level', 'track', 'name'],
            },
        ),
    ]
