# Generated by Django 6.0.8 on 2026-08-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Mater Domini Schools', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='Short phrase shown under the school name, e.g. on the homepage hero.', max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('main_office_phone', models.CharField(blank=True, max_length=30)),
                ('admissions_phone', models.CharField(blank=True, max_length=30)),
                ('emergency_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('result_portal_url', models.URLField(blank=True, help_text='Link to the Student Result Portal (Phase 2). Kept as a URL field so it can point at the new built-in portal once Phase 2 ships.')),
            ],
            options={
                'verbose_name': 'School Information',
                'verbose_name_plural': 'School Information',
            },
        ),
    ]
