# Generated by Django 6.0.8 on 2026-08-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True, help_text="The school's founding story and background.")),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('administrator_name', models.CharField(blank=True, max_length=150)),
                ('administrator_title', models.CharField(blank=True, default='School Administrator', max_length=150)),
                ('administrator_message', models.TextField(blank=True)),
                ('administrator_photo', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('child_name', models.CharField(max_length=150)),
                ('level_applying_for', models.CharField(choices=[('creche', 'Creche'), ('nursery', 'Nursery'), ('primary', 'Primary'), ('jss', 'Junior Secondary'), ('sss', 'Senior Secondary')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Marked once office staff have followed up.')),
            ],
            options={
                'verbose_name_plural': 'Admission Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True, help_text='Documents/requirements needed to apply, one per line.')),
            ],
            options={
                'verbose_name': 'Admissions Page',
                'verbose_name_plural': 'Admissions Page',
            },
        ),
        migrations.CreateModel(
            name='AdmissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
