# Generated by Django 6.1 on 2026-08-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutpage_admissioninquiry_admissionspage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'WASSCE Excellence Award 2025'", max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide without deleting.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
