# Generated by Django 6.0.8 on 2026-08-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_schoolinfo_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolinfo',
            name='hero_image',
        ),
    ]
