# Generated by Django 6.0.8 on 2026-08-31 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_heroslide'),
        ('pages', '0004_remove_schoolinfo_hero_image'),
    ]

    operations = [
    ]
