# Generated by Django 6.0.8 on 2026-08-07 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('role_title', models.CharField(help_text="e.g. 'Vice Principal (Academics)', 'Mathematics Teacher'.", max_length=150)),
                ('category', models.CharField(choices=[('management', 'Management'), ('teaching', 'Teaching Staff'), ('non_teaching', 'Non-Teaching Staff')], max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within their category.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this profile from the public site without deleting it.')),
                ('department', models.ForeignKey(blank=True, help_text='Optional — mainly relevant for teaching staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='academics.department')),
            ],
            options={
                'ordering': ['category', 'order', 'full_name'],
            },
        ),
    ]
